services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: root
      MYSQL_PASSWORD: Mohith@2006
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tuneup
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Mohith@2006
    depends_on:
      - db
    ports:
      - "8085:8080"   # backend exposed on host: 8085
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "3001:3000"   # frontend exposed on host: 3001
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080   # ✅ fixed to container port
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
