version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: musicdb
      MYSQL_USER: musicuser
      MYSQL_PASSWORD: musicpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/musicdb
      SPRING_DATASOURCE_USERNAME: musicuser
      SPRING_DATASOURCE_PASSWORD: musicpass
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    ports:
      - "3001:3000"   # host 3001 → container 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8080
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
